port: 7890
socks-port: 5678
mixed-port: 6789
allow-lan: false
mode: rule               # rule / global / direct / script
log-level: info          # silent / error / warning / info / debug
external-controller: 127.0.0.1:9090
external-ui: ./dashboard # http://{external-controller}/ui
ipv6: false
hosts:
  'mtalk.google.com': 108.177.125.188
  'alt1-mtalk.google.com': 3.3.3.3
  'alt2-mtalk.google.com': 3.3.3.3
  'alt3-mtalk.google.com': 74.125.200.188
  'alt4-mtalk.google.com': 74.125.200.188
  'alt5-mtalk.google.com': 3.3.3.3
  'alt6-mtalk.google.com': 3.3.3.3
  'alt7-mtalk.google.com': 74.125.200.188
  'alt8-mtalk.google.com': 3.3.3.3
  # 'mtalk.google.com': '2404:6800:4008:c07::bc'
  # 'alt1-mtalk.google.com': '2607:f8b0:4023:c0b::bc'
  # 'alt5-mtalk.google.com': '2607:f8b0:4023:1::bc'
  # 'alt7-mtalk.google.com': '2607:f8b0:4002:c03::bc'
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  nameserver-policy:
   #'265.com': '114.114.114.114'
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:        # Reference: https://github.com/vernesong/OpenClash
    # LAN
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    # Router
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - '+.miwifi.com'
    # NTP Service
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'ntp.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - time1.cloud.tencent.com
    # Music Service
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - aqqmusic.tc.qq.com
    - '+.stream.qqmusic.qq.com'
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    # Game Service
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    ## Konami Master Duel
    - '*.mo.konami.net'
    # Other
    - '*.cn'
    - '+.nflxvideo.net'
    # Windows
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    ## QQ Quick Login
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    ## Golang
    - proxy.golang.org
    ## STUN Server
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
  nameserver:
    - 223.5.5.5
    - https://223.5.5.5/dns-query
    - 119.29.29.29
    - https://1.12.12.12/dns-query
  fallback:
    - https://dns.google/dns-query
    - tcp://1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
   #domain:
     #- '+.google.com'
tun:
  enable: false
  stack: system          # or gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53