port: 7890
socks-port: 5678
mixed-port: 6789
allow-lan: false
mode: rule                # rule / global / direct
log-level: info           # silent / error / warning / info / debug
find-process-mode: strict # 
external-controller: 127.0.0.1:9090
external-ui: ./dashboard  # http://{external-controller}/ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
ipv6: true
unified-delay: true
tcp-concurrent: true
geodata-mode: true        # true：mmdb / false: dat
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 168  # hour
geox-url:
  # https://raw.githubusercontent.com/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat" # Required
  # https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-asn.mmdb
  asn: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-asn.mmdb" # Required
  # 2025-05-04 Misunderstanding: I thought setting geodata-mode to true meant only MMDB files (for mmdb and asn) were needed, and otherwise only DAT files (for geoip and geosite).  
  # Actual behavior: Regardless of configuration, Clash always checks for both ASN.mmdb and GeoSite.dat before starting. If asn and geosite are not set, Clash falls back to downloading data from built-in URLs. This is why Clash fails to start in environments without proxy network—it can't retrieve the required GEO files.
  # https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip-only-cn-private.dat
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip-only-cn-private.dat"
  # mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:         # Reference: https://github.com/vernesong/OpenClash
    # LAN
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    # Router
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - '+.miwifi.com'
    # NTP Service
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'ntp.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - time1.cloud.tencent.com
    # Music Service
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - aqqmusic.tc.qq.com
    - '+.stream.qqmusic.qq.com'
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    # Game Service
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    ## Konami Master Duel
    - '*.mo.konami.net'
    # Other
    - '*.cn'
    - '+.nflxvideo.net'
    # Windows
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    ## QQ Quick Login
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    ## Golang
    - proxy.golang.org
    ## STUN Server
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  nameserver:
    - 223.5.5.5
    - https://223.5.5.5/dns-query
    - 119.29.29.29
    - https://1.12.12.12/dns-query
  fallback:
    - https://dns.google/dns-query
    - tcp://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
tun:
  enable: false
  stack: system           # or gvisor