proxies:
  - { "name": "Placeholder", "type": "http", "server": "127.0.0.1:1080", "port": 80 }

proxy-groups:
  - {"name":"JP","type":"fallback","interval":300,"url":"http://connectivitycheck.gstatic.com/generate_204","proxies":["Placeholder"]}
  - {"name":"HK","type":"select","proxies":["Placeholder"]}
  - {"name":"TW","type":"select","proxies":["Placeholder"]}
  - {"name":"US","type":"select","proxies":["Placeholder"]}
  - {"name":"EA","type":"select","proxies":["Placeholder"]}
  - {"name":"XX","type":"select","proxies":["Placeholder"]}
  - {"name":"ALL","type":"url-test","interval":7200,"tolerance":20,"url":"http://youtube.com/generate_204","proxies":["Placeholder"]}
  - {"name":"PROXY","type":"select","proxies":["ALL","HK","JP","TW","US","EA","XX","DIRECT"]}
  - {"name":"NATIVE","type":"select","proxies":["DIRECT","ALL","TW","JP","HK"]}
  - {"name":"OSMEDIA","type":"select","proxies":["ALL","TW","JP","HK","US","PROXY"]}
  - {"name":"RESTRICT","type":"select","proxies":["JP","US","PROXY"]}
  - {"name":"MATCH","type":"select","proxies":["PROXY","DIRECT"]}
  - {"name":"DENIED","type":"select","proxies":["REJECT","NATIVE"]}