config:
  -
    name: Lan
    policy: DIRECT
    inline: true
    priority: 2
  -
    name: Telegram
    policy: PROXY
    inline: true
    priority: 1
  -
    name: TikTok
    policy: TIKTOK
  - 
    name: OverseasMedia
    policy: OSMEDIA
  -
    name: Global
    policy: PROXY
    priority: -1
  - 
    name: China
    policy: DIRECT
    priority: -2
  - 
    name: Microsoft
    policy: PROXY
  -
    name: Steam
    policy: STEAM

rule-providers:
  Lan:
    type: http
    behavior: classical
    path: ./ruleset/Lan.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
    interval: 86400

  AdBlock:
    type: http
    behavior: classical
    path: ./ruleset/AdBlock.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400

  OverseasMedia:
    type: http
    behavior: classical
    path: ./ruleset/OverseasMedia.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/GlobalMedia/GlobalMedia.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./ruleset/Global.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./ruleset/China.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/China/China.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    path: ./ruleset/Microsoft.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400

  Steam:
    type: http
    behavior: classical
    path: ./ruleset/Steam.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    path: ./ruleset/Telegram.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    interval: 86400

  TikTok:
    type: http
    behavior: classical
    path: ./ruleset/TikTok.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml
    interval: 86400