name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * fri"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          # Convert All LF to CRLF, UTF-8 to GBK
          function unix2dos(){
            file="$1"
            echo "Processing '$file' ..."
            iconv -f UTF-8 -t GBK -c "$file" > tmp
            vim tmp -c "set ff=dos" -c ":wq"
            mv -f tmp "$file"
          }
          for el in `ls scripts/*.bat`
          do
            unix2dos "$el"
          done
      - name: Download and Uncompress
        run: |
          clash=$(
            curl -s 'https://api.github.com/repos/Dreamacro/clash/releases/tags/premium' | \
            python -c "import sys, json; src=json.load(sys.stdin); urls=[i['browser_download_url'] for i in src['assets'] if i['name'].find('windows-amd64') > -1]; print(src['name'].split(' ')[1] + ';' + urls[0])"
          )
          release_mark=$(echo $clash|cut -d ";" -f 1)
          release_title="SlimClash ${release_mark}.zip"
          
          RELEASE_DESC="> Based on Clash Premium ${release_mark}, only packaged version amd64 for Windows.
          ## Related Links
          - [Original Release](https://github.com/Dreamacro/clash/releases/tag/premium)
          - [Dashboard Repo](https://github.com/Dreamacro/clash-dashboard)
          - [GeoIP2 · CN](https://github.com/Hackl0us/GeoIP2-CN)"
          
          echo 'RELEASE_DESC<<EOF' >> $GITHUB_ENV
          echo "$RELEASE_DESC" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "RELEASE_TITLE=$release_title" >> $GITHUB_ENV

          curl -Loclash.zip $(echo $clash | cut -d ";" -f 2)
          7z x clash.zip # clash.zip/clash-windows-amd64.exe
          curl -Lodashboard.zip https://github.com/Dreamacro/clash-dashboard/archive/refs/heads/gh-pages.zip
          7z x dashboard.zip
          curl -Logeodb https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb
          curl -Lowt.zip https://github.com/coo11/SlimClash/releases/download/wintools/win_tools.zip
          7z x wt.zip
      - name: Compile config.js
        run: |
          curl -Loqjscu.zip https://github.com/coo11/SlimClash/releases/download/quickjs/qjsc_utils.zip
          7z x qjscu.zip
          cd qjsc_utils
          ./qjsc -e -o config.c -flto -fno-eval ../config.js
          x86_64-w64-mingw32-gcc -s -o config.exe -I./ -L./ -lqjs config.c
      - name: Pack related files
        run: |
          mkdir -p SlimClash/.clash/dashboard/../ruleset/../../.utils/
          mv clash-windows-amd64.exe SlimClash/clash.exe
          mv clash-dashboard-gh-pages/ -T SlimClash/.clash/dashboard/
          mv geodb SlimClash/.clash/country.mmdb
          
          pip install pyyaml
          python parser.py
          
          mv output.yaml SlimClash/.clash/config.yaml
          mv *.yaml -t SlimClash/.clash/ruleset/
          cp qjsc_utils/qjs.dll qjsc_utils/config.exe win_tools/* -t SlimClash/.utils/
          cp src/icon.ico SlimClash/icon.ico
          cp scripts/*.bat scripts/*.vbs -t SlimClash/
          
          7z a -mm=Deflate -mfb=258 -mpass=15 -r SlimClash_rs.zip SlimClash/
          rm -rf SlimClash/.clash/ruleset/*.yaml
          7z a -mm=Deflate -mfb=258 -mpass=15 -r SlimClash.zip SlimClash/
      - name: Update Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: weeklybuild
          prerelease: false
          name: ${{ env.RELEASE_TITLE }}
          body: ${{ env.RELEASE_DESC }}
          files: SlimClash*.zip
