name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * fri"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/setup-python@v4
      #  with:
     #     python-version: '3.11'
      #    cache: 'pip'
      - name: Build
        run: |
          pip install pyyaml
          
          clash=$(
            curl -s 'https://api.github.com/repos/Dreamacro/clash/releases/tags/premium' | \
            python -c "import sys, json; src=json.load(sys.stdin); urls=[i['browser_download_url'] for i in src['assets'] if i['name'].find('windows-amd64') > -1]; print(src['name'].split(' ')[1] + ';' + urls[0])"
          )
          release_mark=$(echo $clash|cut -d ";" -f 1)
          release_title="SlimClash ${release_mark}.zip"
          
          curl -Loclash.zip $(echo $clash | cut -d ";" -f 2)
          7z x clash.zip # clash.zip/clash-windows-amd64.exe
          curl -Lodashboard.zip https://github.com/Dreamacro/clash-dashboard/archive/refs/heads/gh-pages.zip
          7z x dashboard.zip
          curl -Logeodb https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb
          
          mkdir -p SlimClash/.clash/dashboard/../ruleset/../../.utils/
          mv clash-windows-amd64.exe SlimClash/clash.exe
          mv clash-dashboard-gh-pages/ -T SlimClash/.clash/dashboard/
          mv geodb SlimClash/.clash/country.mmdb
          
          python parser.py
          mv output.yaml SlimClash/.clash/config.yaml
          cp config.js bin/* -t SlimClash/.utils/
          cp src/icon.ico SlimClash/clash.ico
          cp scripts/* -t SlimClash/
          
          7z a -mm=Deflate -mfb=258 -mpass=15 -r SlimClash.zip SlimClash/
          RELEASE_DESC="> Based on Clash Premium ${release_mark}, only packaged version amd64 for Windows.
          ## Related Links
          - [Original Release](https://github.com/Dreamacro/clash/releases/tag/premium)
          - [Dashboard Repo](https://github.com/Dreamacro/clash-dashboard)
          - [GeoIP2 · CN](https://github.com/Hackl0us/GeoIP2-CN)"
          
          echo 'RELEASE_DESC<<EOF' >> $GITHUB_ENV
          echo "$RELEASE_DESC" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "RELEASE_TITLE=$release_title" >> $GITHUB_ENV
      - name: Update Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: weeklybuild
          prerelease: false
          name: ${{ env.RELEASE_TITLE }}
          body: ${{ env.RELEASE_DESC }}
          files: SlimClash.zip
